<?php
/**
 * Copyright © MageKey. All rights reserved.
 */

?>
<div id="mgkAdcPopup" data-bind="scope:'mgkAdcPopup'" style="display: none;">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#mgkAdcPopup": {
                "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
            },
            "*": {
                "Magento_Ui/js/block-loader": "<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>"
            }
        }
    </script>
</div>
